version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:urlshort@db:5432/UrlShortner
      REDIS_URL: rediss://default:ASw-AAIjcDFhYzQ1YTc0ZDI1M2I0NzAxOWEwYjM1NjFjNTlkNjQ4N3AxMA@amused-kiwi-11326.upstash.io:6379
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: urlshort
      POSTGRES_DB: UrlShortner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
